name: electron-wallet
version: '0.1'
summary: Destroy your opponent's castle to win!
description: |
 Play online or against a bot, click and drag cards to your side of the field
 to deploy powerful buildings and units to attack your enemy.

confinement: strict
grade: stable
base: core18

parts:
  electron-app:
    plugin: nodejs
    source: .

    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - qtwayland5
      - ca-certificates

    build-packages:
      - curl
      - wget
      - gcc
      - gcc-8
      - g++
      - g++-8
      - make
      - autoconf
      - automake
      - cmake
      - pkg-config
      - libtool
      - bsdmainutils
      - binutils
      - python3
      - help2man
      - doxygen
      - npm
      - libts-dev
      - vim
      - git

#    build: node_modules/.bin/electron-builder
#    install: |
#      mkdir $SNAPCRAFT_PART_INSTALL/app
#      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
#    prime:
#      - -node_modules

apps:
  electron-wallet:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/electron-wallet
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
